# Generated by Django 4.2.7 on 2024-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('modalidade', models.CharField(choices=[('ENS', 'Ensino'), ('PES', 'Pesquisa'), ('EXT', 'Extensão')], max_length=3)),
                ('descricao', models.CharField(max_length=250)),
                ('ch_min', models.IntegerField()),
                ('ch_max', models.IntegerField()),
                ('ap_max', models.IntegerField()),
            ],
        ),
    ]
