# Generated by Django 4.2.7 on 2024-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
